spring:
  application:
    name: Grievance-Service
  data:
    mongodb:
      database: grievanceDb
  webflux:
    multipart:
      max-in-memory-size: 20MB
  codec:
    max-in-memory-size: 20MB

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true

departments:
  service:
    base-url: http://auth-service:9007
    path: /api/auth/departments

auth:
  service:
    base-url: http://auth-service:9007
    profile-path: /api/auth/profile
