spring:
  application:
    name: Grievance-Service
  data:
    mongodb:
      database: grievanceDb

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true

departments:
  service:
    base-url: http://departments-json:3001/
