spring:
  application:
    name: Notification-Service
  data:
    mongodb:
      database: notificationDb
  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.notifiction.event.GrievanceEvent
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:rajat.contact.rajat@gmail.cor}
    password: ${MAIL_PASSWORD:sejifzxgvdzpmabf}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET:change-this-auth-secret-key-please-32-chars}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:ACclef8eaaf22404b46a51c08c572cc5d5}
  auth-token: ${TWILIO_AUTH_TOKEN:c44fdfab79198aa0799d680c0cfc12ef}
  from: ${TWILIO_FROM:+17654154397}
  to: ${TWILIO_TO:+917651881382}

mail:
  from: ${MAIL_FROM:rajat.contact.rajat@gmail.com}
  to: ${MAIL_TO:rajat.contact.rajat@gmail.com}
