spring:
  application:
    name: Storage-Service
  data:
    mongodb:
      database: notificationDb
  webflux:
    multipart:
      max-in-memory-size: 20MB
  codec:
    max-in-memory-size: 20MB

server:
  port: 9003

eureka:
  instance:
    prefer-ip-address: true

grievance:
  service:
    url: ${GRIEVANCE_URL:http://localhost:9001}

jwt:
  secret: ${JWT_SECRET:change-this-auth-secret-key-please-32-chars}
