// Configured according to Linux VM on Azure
pipeline {
    agent any
    triggers {
        githubPush()
    }

    tools {
        maven 'maven-3.9.0'
        jdk 'jdk-17'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/kanchanraiii/EGOVGRIEVANCE_BACKEND.git'
            }
        }

        stage('Create secrets.properties') {
            steps {
                withCredentials([
                    string(credentialsId: 'notif_jwt_secret', variable: 'JWT_SECRET'),
                    string(credentialsId: 'twilio_sid',       variable: 'TWILIO_SID'),
                    string(credentialsId: 'twilio_token',     variable: 'TWILIO_TOKEN'),
                    string(credentialsId: 'twilio_from',      variable: 'TWILIO_FROM'),
                    string(credentialsId: 'twilio_to',        variable: 'TWILIO_TO'),
                    string(credentialsId: 'smtp_username',    variable: 'SMTP_USER'),
                    string(credentialsId: 'smtp_password',    variable: 'SMTP_PASS'),
                    string(credentialsId: 'mail_from',        variable: 'MAIL_FROM'),
                    string(credentialsId: 'mail_to',          variable: 'MAIL_TO')
                ]) {
                    sh '''
                      cat > secrets.properties <<EOF
# Secrets override file (generated by Jenkins)
jwt.secret=${JWT_SECRET}

twilio.account-sid=${TWILIO_SID}
twilio.auth-token=${TWILIO_TOKEN}
twilio.from=${TWILIO_FROM}
twilio.to=${TWILIO_TO}

spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
mail.from=${MAIL_FROM}
mail.to=${MAIL_TO}
EOF
                      chmod 600 secrets.properties
                    '''
                }
            }
        }

        stage('Build All Services (Maven)') {
            steps {
                sh '''
                  mvn -f Eureka-Server/pom.xml package
                  mvn -f Config-Server/pom.xml package
                  mvn -f Api-Gateway/pom.xml package
                  mvn -f Auth-Service/pom.xml package
                  mvn -f Grievance-Service/pom.xml package
                  mvn -f Feedback-Service/pom.xml package
                  mvn -f Notification-Service/pom.xml package
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Restart Containers') {
            steps {
                sh '''
                  docker compose down || true
                  docker compose up -d
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            // Optional cleanup (uncomment if you want to remove secrets file after deploy)
            // sh 'rm -f secrets.properties || true'
        }
        failure {
            sh 'docker compose down || true'
        }
        success {
            echo 'EGOV Grievance Backend is UP and running'
        }
    }
}
